version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: teamovictor_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - teamovictor-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: robotica_backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=1433
      - DB_NAME=proyectointerdisciplinar
      - DB_USER=sa
      - DB_PASSWORD=YourStrong!Passw0rd
      - PORT=3000
    volumes:
      - ./Base de Datos.sql:/app/init.sql:ro
    depends_on:
      - db
    networks:
      - teamovictor-network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql
    networks:
      - teamovictor-network

networks:
  teamovictor-network:
    driver: bridge

volumes:
  db_data:
